version: '3'
services:
  web:
    image: php
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
